In [7]:
import pandas as pd
import re

#### Helper Function

In [45]:
def discount_calculation(row):

    discount_df = row['優惠']
    price_df = row['價格']
    
    match_pattern_1 = re.search(r"^((?P<X>\d+(\.\d+)?)\s*折)$", discount_df)
    match_pattern_2 = re.search(r"^(買(?P<qty>\d+(\.\d+)?)\s*件\s*\$(?P<price>\d+(\.\d+)?))$", discount_df)
    match_pattern_3 = re.search(r"^((?P<dash>-))$", discount_df)
    match_pattern_4 = re.search(r"^(\$(?P<price>\d+(?:\.\d+)?)任揀(?P<qty1>\d+(?:\.\d+)?)件\s*/\s*買(?P<qty2>\d+(?:\.\d+)?)件享(?P<discount>\d+(?:\.\d+)?)%折扣)$", discount_df)
    match_pattern_5 = re.search(r"Buy\s+(?P<qty>\d+(?:\.\d+)?)\s+item(?:s)?\s+for\s+\$(?P<price>\d+(?:\.\d+)?)", discount_df)
    match_pattern_6 = re.search(r"^(任揀(?P<qty>\d+(?:\.\d+)?)件)$", discount_df)
    match_pattern_7 = re.search(r"^(買(?P<qty>\d+(?:\.\d+)?)\s*件\s*享\s*(?P<discount>\d+(?:\.\d+)?)\s*%\s*折扣)$", discount_df)
    match_pattern_8 = re.search(r"^(\$(?P<price>\d+(\.\d+)?)任揀(?P<qty>\d+(\.\d+)?)件)$", discount_df)
    match_pattern_9 = re.search(r"^(精選Merries TapesPants買(?P<qty>\d+(?:\.\d+)?)件送(?P<free_qty>\d+(?:\.\d+)?)件)$", discount_df)
    match_pattern_10 = re.search(r"^(精選Baby Products買(?P<buy>\d+(\.\d+)?)件送(?P<gift>\d+(\.\d+)?)件)$", discount_df)
    match_pattern_11 = re.search(r"^(精選好奇天然透氣學習褲(?P<qty>\d+(\.\d+)?)件(?P<discount>\d+(\.\d+)?)折)$", discount_df)
    match_pattern_12 = re.search(r"^(精選口腔護理產品買(?P<qty>\d+(?:\.\d+)?)件(?P<discount>\d+(?:\.\d+)?)折)$", discount_df)
    match_pattern_13 = re.search(r"^(精選Sanitary Products買(?P<buy_qty>\d+(\.\d+)?)\s*件送(?P<gift_qty>\d+(\.\d+)?)\s*件)$", discount_df)
    match_pattern_14 = re.search(r"^(精選女性衛生護理產品買(?P<qty>\d+(\.\d+)?)件(?P<discount>\d+(\.\d+)?)折)$", discount_df)
    match_pattern_15 = re.search(r"^(精選幫寶適尿片拉拉褲買(?P<qty>\d+(?:\.\d+)?)件(?P<discount>\d+(?:\.\d+)?)折)$", discount_df)
    match_pattern_16 = re.search(r"^(精選Haircare Products買(?P<buy_qty>\d+(?:\.\d+)?)\s*件\s*送\s*(?P<free_qty>\d+(?:\.\d+)?)\s*件)$", discount_df)
    match_pattern_17 = re.search(r"^(精選Baby Food Product買(?P<buy_qty>\d+(\.\d+)?)件送(?P<gift_qty>\d+(\.\d+)?)件)$", discount_df)
    match_pattern_18 = re.search(r"^(精選Wyeth\s*SX\s*ULTIMA買(?P<buy_qty>\d+(?:\.\d+)?)件送(?P<gift_qty>\d+(?:\.\d+)?)件)$", discount_df)
    match_pattern_19 = re.search(r"^(精選護膚產品買(?P<qty>\d+(?:\.\d+)?)件(?P<discount>\d+(?:\.\d+)?)折)$", discount_df)
    match_pattern_20 = re.search(r"^(精選嬰兒產品買(?P<qty>\d+(\.\d+)?)\s*件\s*(?P<discount>\d+(\.\d+)?)\s*折)$", discount_df)
    match_pattern_21 = re.search(r"^(精選Skincare Products買(?P<buy_qty>\d+(?:\.\d+)?)件送(?P<gift_qty>\d+(?:\.\d+)?)件)$", discount_df)
    match_pattern_22 = re.search(r"^(精選中藥產品買(?P<qty>\d+(?:\.\d+)?)\s*件\s*(?P<discount>\d+(?:\.\d+)?)\s*折)$", discount_df)
    match_pattern_23 = re.search(r"^(精選西式藥品買(?P<qty>\d+(?:\.\d+)?)件\s*(?P<discount>\d+(?:\.\d+)?)折)$", discount_df)
    match_pattern_24 = re.search(r"^(精選龍角散產品買(?P<qty>\d+(\.\d+)?)件(?P<discount>\d+(\.\d+)?)折)$", discount_df)
    match_pattern_25 = re.search(r"^(精選中式滋補產品買(?P<qty>\d+(\.\d+)?)\s*件\s*(?P<discount>\d+(\.\d+)?)\s*折)$", discount_df)
    match_pattern_26 = re.search(r"^(精選維柏健產品買(?P<qty>\d+(\.\d+)?)件(?P<discount>\d+(\.\d+)?)折)$", discount_df)
    match_pattern_27 = re.search(r"^(精選Biostime\s+Probiotics買(?P<buy_qty>\d+(?:\.\d+)?)件送(?P<gift_qty>\d+(?:\.\d+)?)件)$", discount_df)
    match_pattern_28 = re.search(r"^(精選BM\s*Probiotics買(?P<buy_qty>\d+(?:\.\d+)?)\s*件送(?P<gift_qty>\d+(?:\.\d+)?)\s*件)$", discount_df)
    match_pattern_29 = re.search(r"^(精選Health Product買(?P<buy_qty>\d+(\.\d+)?)\s*件送(?P<gift_qty>\d+(\.\d+)?)\s*件)$", discount_df)
    match_pattern_30 = re.search(r"^(買第二件享(?P<discount>\d+(\.\d+)?)%折扣)$", discount_df)
    match_pattern_31 = re.search(r"^(全線家居防蚊用品買(?P<qty>\d+(\.\d+)?)件，可享(?P<discount>\d+(\.\d+)?)折優惠。)$", discount_df)
    match_pattern_32 = re.search(r"^(買第(?P<qty>\d+(?:\.\d+)?)件\s*\$(?P<price>\d+(?:\.\d+)?))$", discount_df)
    match_pattern_33 = re.search(r"^(買(?P<qty>\d+(\.\d+)?)\s*件\s*慳\s*\$(?P<price>\d+(\.\d+)?))$", discount_df)
    match_pattern_34 = re.search(r"^(Buy\s+(?P<amount>\d+(?:\.\d+)?)\s+to\s+save\s+\$(?P<save>\d+(?:\.\d+)?))$", discount_df)
    match_pattern_35 = re.search(r"^(買(?P<qty>\d+(\.\d+)?)\s*件\s*送\s*(?P<gift>\d+(\.\d+)?)\s*件)$", discount_df)
    match_pattern_36 = re.search(r"^(買(?P<buy>\d+(?:\.\d+)?)\s*送(?P<gift>\d+(?:\.\d+)?))$", discount_df)
    match_pattern_37 = re.search(r"^(買(?P<buy_qty>\d+(?:\.\d+)?)送(?P<gift_qty>\d+(?:\.\d+)?).*?請輸入(?P<input_qty>\d+(?:\.\d+)?)件.*?送價低者.*?Neutrogena 深層保濕面膜\s*(?P<pack_qty>\d+(?:\.\d+)?)片裝)$", discount_df)
    match_pattern_38 = re.search(r"^(第(?P<index>\d+(\.\d+)?)件半價)$", discount_df)
    match_pattern_39 = re.search(r"^(買(?P<qty>\d+(?:\.\d+)?)\s*件只需\$(?P<price>\d+(?:\.\d+)?))$", discount_df)
    match_pattern_40 = re.search(r"^(第二件(?P<discount>\d+(\.\d+)?)%\s*折扣)$", discount_df)
    match_pattern_41 = re.search(r"^(買(?P<qty>\d+(?:\.\d+)?)件或以上(?P<discount>\d+(?:\.\d+)?)折)$", discount_df)
    match_pattern_42 = re.search(r"^(買(?P<qty>\d+(?:\.\d+)?)\s*送\s*(?P<gift>\d+(?:\.\d+)?))$", discount_df)
    match_pattern_43 = re.search(r"(?P<total>\d+)件.*?(?P<gift>\d+)件.*?(免費|送)", discount_df)
    match_pattern_44 = re.search(r"買\s*(?P<buy>\d+(?:\.\d+)?)\s*.*?\s*送\s*(?P<give>\d+(?:\.\d+)?)", discount_df)
    match_pattern_45 = re.search(r"買\s*(?P<quantity>\d+)\s*件\s*.*?\s*(?P<discount>\d+(?:\.\d+)?)\s*折", discount_df)
    match_pattern_46 = re.search(r"(?P<quantity>\d+)\s*件\s*(?:或以上|起)?\s*.*?\s*(?P<discount>\d+(?:\.\d+)?)\s*折", discount_df)
                    
    if match_pattern_2:
        temp = match_pattern_2
        text_quantity = temp.group('qty')
        text_price = temp.group('price')
        text = f'${text_price}/{text_quantity}件'
    
    elif match_pattern_4:
        temp = match_pattern_4
        text_price = temp.group('price')
        text_quantity_1 = temp.group('qty1')
        text_quantity_2 = temp.group('qty2')
        text_discount = str(float('0.' + str(100 - int(temp.group('discount'))))*100).replace('0', '').replace('.', '')
        text = f'${text_price}/{text_quantity_1}件 或 {text_quantity_2}件/{text_discount}折'

    elif match_pattern_5:
        temp = match_pattern_5
        text_quantity = temp.group('qty')
        text_price = temp.group('price')
        text = f'${text_price}/{text_quantity}件'
        
    elif match_pattern_7:
        temp = match_pattern_7       
        text_quantity = temp.group('qty')
        text_discount = int((100 - int(temp.group('discount')))/100 * int(text_quantity) * price_df)
        text = f'${text_discount}/{text_quantity}件' 
        
    elif match_pattern_8:
        temp = match_pattern_8     
        text_quantity = temp.group('qty')
        text_price = temp.group('price')
        text = f'${text_price}/{text_quantity}件'
        
    elif match_pattern_9:
        temp = match_pattern_9    
        text_quantity = temp.group('qty')
        text_quantity_free = temp.group('free_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'
         
    elif match_pattern_10:
        temp = match_pattern_10    
        text_quantity = temp.group('buy')
        text_quantity_free = temp.group('gift')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_11:
        temp = match_pattern_11    
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'
         
    elif match_pattern_12:
        temp = match_pattern_12   
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_13:
        temp = match_pattern_13   
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('gift_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_14:
        temp = match_pattern_14   
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件' 
        
    elif match_pattern_15:
        temp = match_pattern_15   
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_16:
        temp = match_pattern_16   
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('free_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_17:
        temp = match_pattern_17   
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('gift_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_18:
        temp = match_pattern_18   
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('gift_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_19:
        temp = match_pattern_19   
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'
     
    elif match_pattern_20:
        temp = match_pattern_20   
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件' 

    elif match_pattern_21:
        temp = match_pattern_21   
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('gift_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_22:
        temp = match_pattern_22  
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_23:
        temp = match_pattern_23  
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_24:
        temp = match_pattern_24  
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_25:
        temp = match_pattern_25  
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件' 
        
    elif match_pattern_26:
        temp = match_pattern_26  
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件'   

    elif match_pattern_27:
        temp = match_pattern_27  
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('gift_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件' 
        
    elif match_pattern_28:
        temp = match_pattern_28  
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('gift_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_29:
        temp = match_pattern_29  
        text_quantity = temp.group('buy_qty')
        text_quantity_free = temp.group('gift_qty')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_30:
        temp = match_pattern_30  
        text_discount = int(float('0.' + temp.group('discount')) * price_df + price_df)
        text = f'${text_discount}/2件'  
        
    elif match_pattern_31:
        temp = match_pattern_31  
        text_quantity = temp.group('qty')
        text_discount = int(float('0.' + temp.group('discount')) * price_df * int(text_quantity))
        text = f'${text_discount}/{text_quantity}件' 
        
    elif match_pattern_32:
        temp = match_pattern_32  
        text_quantity = temp.group('qty')
        text_discount = int(price_df * int(text_quantity) - price_df + int(temp.group('price')))
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_33:
        temp = match_pattern_33  
        text_quantity = temp.group('qty')
        text_discount = int(price_df * int(text_quantity) - int(float(temp.group('price'))))
        text = f'${text_discount}/{text_quantity}件'   
        
    elif match_pattern_34:
        temp = match_pattern_34  
        text_quantity = temp.group('amount')
        text_discount = int(price_df * int(text_quantity) - int(float(temp.group('save'))))
        text = f'${text_discount}/{text_quantity}件' 
        
    elif match_pattern_35:
        temp = match_pattern_35  
        text_quantity = temp.group('qty')
        text_quantity_free = temp.group('gift')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'
        
    elif match_pattern_38:
        temp = match_pattern_38  
        text_quantity = temp.group('index')
        text_discount = int(price_df * int(text_quantity) - price_df * 0.5)
        text = f'${text_discount}/{text_quantity}件'    
        
    elif match_pattern_39:
        temp = match_pattern_39  
        text_quantity = temp.group('qty')
        text_price = temp.group('price')
        text = f'${text_price}/{text_quantity}件'
        
    elif match_pattern_40:
        temp = match_pattern_40  
        text_discount = int(float('0.' + temp.group('discount')) * price_df + price_df)
        text = f'${text_discount}/2件'
        
    elif match_pattern_41:
        temp = match_pattern_41
        text_quantity = temp.group('qty')
        text_discount = temp.group('discount')
        text = f'{text_discount}折/{text_quantity}件或以上'     

    elif match_pattern_42:
        temp = match_pattern_42
        text_quantity = temp.group('qty')
        text_quantity_free = temp.group('gift')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_43:
        temp = match_pattern_43
        text_quantity = temp.group('total')
        text_quantity_free = temp.group('gift')
        text_quantity_price = int(text_quantity) - int(text_quantity_free)
        text_discount = int(price_df * int(text_quantity_price))
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_44:
        temp = match_pattern_44
        text_quantity = temp.group('buy')
        text_quantity_free = temp.group('give')
        text_discount = int(price_df * int(text_quantity))
        text_quantity = int(text_quantity) + int(text_quantity_free)
        # text = f'買{text_quantity}送{text_quantity_free}'
        text = f'${text_discount}/{text_quantity}件'

    elif match_pattern_45:
        temp = match_pattern_45
        text_quantity = temp.group('quantity')
        text_discount = temp.group('discount')
        text_discount = int(price_df * int(text_quantity) * float('0.' + text_discount))
        text = f'${text_discount}/{text_quantity}件'
    
    elif match_pattern_46:
        temp = match_pattern_46
        text_quantity = temp.group('quantity')
        text_discount = temp.group('discount')
        text = f'{text_discount}折/{text_quantity}件或以上'   

    else:
        text = row['優惠']
        
    return text

#### Datasets

In [46]:
df = pd.read_csv("https://online-price-watch.consumer.org.hk/opw/opendata/pricewatch_zh-Hant.csv")
df['Name'] = df['品牌'] + ' - ' + df['貨品名稱']

df['優惠'] = df['優惠'].fillna('-')
df['discount_v2'] = df.apply(discount_calculation, axis = 1)
df['discount_v2'] = df['discount_v2'].apply(lambda x: x.replace('.00', '').replace('.0', ''))

df_na = df[df['優惠'] == '-']
df_na['price_discount'] = df_na['價格'].astype(str)
df_not_na = df[~(df['優惠'] == '-')]
df_not_na['price_discount'] = df_not_na['價格'].astype(str) + ' (' + df_not_na['discount_v2'] + ')'
df = pd.concat([df_na, df_not_na], ignore_index = False)

C:\Users\kwan_\AppData\Local\Temp\ipykernel_9420\2088060718.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_na['price_discount'] = df_na['價格'].astype(str)
C:\Users\kwan_\AppData\Local\Temp\ipykernel_9420\2088060718.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_na['price_discount'] = df_not_na['價格'].astype(str) + ' (' + df_not_na['discount_v2'] + ')'

In [21]:
# df['show'] = df['優惠'].str.replace(r'[-+]?\d+(\.\d+)?', 'X', regex=True)
# temp = pd.DataFrame()
# temp['show'] = df['show'].unique()
# temp

In [50]:
df[df['Name'] == '金寶 - 卡邦尼蘑菇意粉醬 295克 10.4安士']

,貨品分類1,貨品分類2,貨品分類3,貨品編號,品牌,貨品名稱,超市代號,價格,優惠,Name,discount_v2,price_discount,show
2651,粉麵 / 煮食用料 / 冷凍加工食品,調味 / 煮食用料,意粉醬,P000003503,金寶,卡邦尼蘑菇意粉醬 295克 10.4安士,DCHFOOD,15.0,-,金寶 - 卡邦尼蘑菇意粉醬 295克 10.4安士,-,15.0,-
2647,粉麵 / 煮食用料 / 冷凍加工食品,調味 / 煮食用料,意粉醬,P000003503,金寶,卡邦尼蘑菇意粉醬 295克 10.4安士,WELLCOME,20.0,$30任揀3件,金寶 - 卡邦尼蘑菇意粉醬 295克 10.4安士,$30/3件,20.0 ($30/3件),$X/X件
2648,粉麵 / 煮食用料 / 冷凍加工食品,調味 / 煮食用料,意粉醬,P000003503,金寶,卡邦尼蘑菇意粉醬 295克 10.4安士,PARKNSHOP,17.0,買3件慳$18.00,金寶 - 卡邦尼蘑菇意粉醬 295克 10.4安士,$33/3件,17.0 ($33/3件),$X/X件
2649,粉麵 / 煮食用料 / 冷凍加工食品,調味 / 煮食用料,意粉醬,P000003503,金寶,卡邦尼蘑菇意粉醬 295克 10.4安士,JASONS,20.5,$30任揀3件,金寶 - 卡邦尼蘑菇意粉醬 295克 10.4安士,$30/3件,20.5 ($30/3件),$X/X件
2650,粉麵 / 煮食用料 / 冷凍加工食品,調味 / 煮食用料,意粉醬,P000003503,金寶,卡邦尼蘑菇意粉醬 295克 10.4安士,AEON,16.9,買4件$40.00,金寶 - 卡邦尼蘑菇意粉醬 295克 10.4安士,$40/4件,16.9 ($40/4件),$X/X件

In [47]:
text = df[df['Name'] == 'MEADOWS HOME - 卡通迷你紙巾 12包']['優惠'].tolist()[0]
match_pattern_43 = re.search(r"(?P<total>\d+)件.*?(?P<gift>\d+)件.*?(免費|送)", text)

In [48]:
match_pattern_43.group('total')

'2'

In [49]:
df['show'] = df['discount_v2'].str.replace(r'[-+]?\d+(\.\d+)?', 'X', regex=True)
temp = pd.DataFrame()
temp['show'] = df['show'].unique()
temp

            show
0              -
1          $X/X件
2  $X/X件 或 X件/X折
3             X折
4       X折/X件或以上